# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vladimir/Documents/CPlus/Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vladimir/Documents/CPlus/Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vladimir/Documents/CPlus/Game/CMakeFiles /home/vladimir/Documents/CPlus/Game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vladimir/Documents/CPlus/Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_app

# Build rule for target.
my_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_app
.PHONY : my_app

# fast build rule for target.
my_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/build
.PHONY : my_app/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/fmt-build/CMakeFiles/fmt.dir/build.make _deps/fmt-build/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build.make _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

_deps/imgui-src/backends/imgui_impl_glfw.o: _deps/imgui-src/backends/imgui_impl_glfw.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.o

_deps/imgui-src/backends/imgui_impl_glfw.i: _deps/imgui-src/backends/imgui_impl_glfw.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.i

_deps/imgui-src/backends/imgui_impl_glfw.s: _deps/imgui-src/backends/imgui_impl_glfw.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.s

_deps/imgui-src/backends/imgui_impl_opengl3.o: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.o

_deps/imgui-src/backends/imgui_impl_opengl3.i: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i

_deps/imgui-src/backends/imgui_impl_opengl3.s: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.o: _deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.o

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.cpp.o

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

_deps_external/glad/src/glad.o: _deps_external/glad/src/glad.c.o
.PHONY : _deps_external/glad/src/glad.o

# target to build an object file
_deps_external/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/_deps_external/glad/src/glad.c.o
.PHONY : _deps_external/glad/src/glad.c.o

_deps_external/glad/src/glad.i: _deps_external/glad/src/glad.c.i
.PHONY : _deps_external/glad/src/glad.i

# target to preprocess a source file
_deps_external/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/_deps_external/glad/src/glad.c.i
.PHONY : _deps_external/glad/src/glad.c.i

_deps_external/glad/src/glad.s: _deps_external/glad/src/glad.c.s
.PHONY : _deps_external/glad/src/glad.s

# target to generate assembly for a file
_deps_external/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/_deps_external/glad/src/glad.c.s
.PHONY : _deps_external/glad/src/glad.c.s

_deps_external/stb_image/src/stb_image_impl.o: _deps_external/stb_image/src/stb_image_impl.c.o
.PHONY : _deps_external/stb_image/src/stb_image_impl.o

# target to build an object file
_deps_external/stb_image/src/stb_image_impl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/_deps_external/stb_image/src/stb_image_impl.c.o
.PHONY : _deps_external/stb_image/src/stb_image_impl.c.o

_deps_external/stb_image/src/stb_image_impl.i: _deps_external/stb_image/src/stb_image_impl.c.i
.PHONY : _deps_external/stb_image/src/stb_image_impl.i

# target to preprocess a source file
_deps_external/stb_image/src/stb_image_impl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/_deps_external/stb_image/src/stb_image_impl.c.i
.PHONY : _deps_external/stb_image/src/stb_image_impl.c.i

_deps_external/stb_image/src/stb_image_impl.s: _deps_external/stb_image/src/stb_image_impl.c.s
.PHONY : _deps_external/stb_image/src/stb_image_impl.s

# target to generate assembly for a file
_deps_external/stb_image/src/stb_image_impl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image.dir/build.make CMakeFiles/stb_image.dir/_deps_external/stb_image/src/stb_image_impl.c.s
.PHONY : _deps_external/stb_image/src/stb_image_impl.c.s

src/app/Core/Graphics/Shader/shader.o: src/app/Core/Graphics/Shader/shader.cpp.o
.PHONY : src/app/Core/Graphics/Shader/shader.o

# target to build an object file
src/app/Core/Graphics/Shader/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Shader/shader.cpp.o
.PHONY : src/app/Core/Graphics/Shader/shader.cpp.o

src/app/Core/Graphics/Shader/shader.i: src/app/Core/Graphics/Shader/shader.cpp.i
.PHONY : src/app/Core/Graphics/Shader/shader.i

# target to preprocess a source file
src/app/Core/Graphics/Shader/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Shader/shader.cpp.i
.PHONY : src/app/Core/Graphics/Shader/shader.cpp.i

src/app/Core/Graphics/Shader/shader.s: src/app/Core/Graphics/Shader/shader.cpp.s
.PHONY : src/app/Core/Graphics/Shader/shader.s

# target to generate assembly for a file
src/app/Core/Graphics/Shader/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Shader/shader.cpp.s
.PHONY : src/app/Core/Graphics/Shader/shader.cpp.s

src/app/Core/Graphics/Texture/texture.o: src/app/Core/Graphics/Texture/texture.cpp.o
.PHONY : src/app/Core/Graphics/Texture/texture.o

# target to build an object file
src/app/Core/Graphics/Texture/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Texture/texture.cpp.o
.PHONY : src/app/Core/Graphics/Texture/texture.cpp.o

src/app/Core/Graphics/Texture/texture.i: src/app/Core/Graphics/Texture/texture.cpp.i
.PHONY : src/app/Core/Graphics/Texture/texture.i

# target to preprocess a source file
src/app/Core/Graphics/Texture/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Texture/texture.cpp.i
.PHONY : src/app/Core/Graphics/Texture/texture.cpp.i

src/app/Core/Graphics/Texture/texture.s: src/app/Core/Graphics/Texture/texture.cpp.s
.PHONY : src/app/Core/Graphics/Texture/texture.s

# target to generate assembly for a file
src/app/Core/Graphics/Texture/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Texture/texture.cpp.s
.PHONY : src/app/Core/Graphics/Texture/texture.cpp.s

src/app/Core/Graphics/Vertex/EBO.o: src/app/Core/Graphics/Vertex/EBO.cpp.o
.PHONY : src/app/Core/Graphics/Vertex/EBO.o

# target to build an object file
src/app/Core/Graphics/Vertex/EBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/EBO.cpp.o
.PHONY : src/app/Core/Graphics/Vertex/EBO.cpp.o

src/app/Core/Graphics/Vertex/EBO.i: src/app/Core/Graphics/Vertex/EBO.cpp.i
.PHONY : src/app/Core/Graphics/Vertex/EBO.i

# target to preprocess a source file
src/app/Core/Graphics/Vertex/EBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/EBO.cpp.i
.PHONY : src/app/Core/Graphics/Vertex/EBO.cpp.i

src/app/Core/Graphics/Vertex/EBO.s: src/app/Core/Graphics/Vertex/EBO.cpp.s
.PHONY : src/app/Core/Graphics/Vertex/EBO.s

# target to generate assembly for a file
src/app/Core/Graphics/Vertex/EBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/EBO.cpp.s
.PHONY : src/app/Core/Graphics/Vertex/EBO.cpp.s

src/app/Core/Graphics/Vertex/VAO.o: src/app/Core/Graphics/Vertex/VAO.cpp.o
.PHONY : src/app/Core/Graphics/Vertex/VAO.o

# target to build an object file
src/app/Core/Graphics/Vertex/VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/VAO.cpp.o
.PHONY : src/app/Core/Graphics/Vertex/VAO.cpp.o

src/app/Core/Graphics/Vertex/VAO.i: src/app/Core/Graphics/Vertex/VAO.cpp.i
.PHONY : src/app/Core/Graphics/Vertex/VAO.i

# target to preprocess a source file
src/app/Core/Graphics/Vertex/VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/VAO.cpp.i
.PHONY : src/app/Core/Graphics/Vertex/VAO.cpp.i

src/app/Core/Graphics/Vertex/VAO.s: src/app/Core/Graphics/Vertex/VAO.cpp.s
.PHONY : src/app/Core/Graphics/Vertex/VAO.s

# target to generate assembly for a file
src/app/Core/Graphics/Vertex/VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/VAO.cpp.s
.PHONY : src/app/Core/Graphics/Vertex/VAO.cpp.s

src/app/Core/Graphics/Vertex/VBO.o: src/app/Core/Graphics/Vertex/VBO.cpp.o
.PHONY : src/app/Core/Graphics/Vertex/VBO.o

# target to build an object file
src/app/Core/Graphics/Vertex/VBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/VBO.cpp.o
.PHONY : src/app/Core/Graphics/Vertex/VBO.cpp.o

src/app/Core/Graphics/Vertex/VBO.i: src/app/Core/Graphics/Vertex/VBO.cpp.i
.PHONY : src/app/Core/Graphics/Vertex/VBO.i

# target to preprocess a source file
src/app/Core/Graphics/Vertex/VBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/VBO.cpp.i
.PHONY : src/app/Core/Graphics/Vertex/VBO.cpp.i

src/app/Core/Graphics/Vertex/VBO.s: src/app/Core/Graphics/Vertex/VBO.cpp.s
.PHONY : src/app/Core/Graphics/Vertex/VBO.s

# target to generate assembly for a file
src/app/Core/Graphics/Vertex/VBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/app/Core/Graphics/Vertex/VBO.cpp.s
.PHONY : src/app/Core/Graphics/Vertex/VBO.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_app.dir/build.make CMakeFiles/my_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... fmt"
	@echo "... glfw"
	@echo "... glm"
	@echo "... imgui"
	@echo "... my_app"
	@echo "... stb_image"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.o"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
	@echo "... _deps_external/glad/src/glad.o"
	@echo "... _deps_external/glad/src/glad.i"
	@echo "... _deps_external/glad/src/glad.s"
	@echo "... _deps_external/stb_image/src/stb_image_impl.o"
	@echo "... _deps_external/stb_image/src/stb_image_impl.i"
	@echo "... _deps_external/stb_image/src/stb_image_impl.s"
	@echo "... src/app/Core/Graphics/Shader/shader.o"
	@echo "... src/app/Core/Graphics/Shader/shader.i"
	@echo "... src/app/Core/Graphics/Shader/shader.s"
	@echo "... src/app/Core/Graphics/Texture/texture.o"
	@echo "... src/app/Core/Graphics/Texture/texture.i"
	@echo "... src/app/Core/Graphics/Texture/texture.s"
	@echo "... src/app/Core/Graphics/Vertex/EBO.o"
	@echo "... src/app/Core/Graphics/Vertex/EBO.i"
	@echo "... src/app/Core/Graphics/Vertex/EBO.s"
	@echo "... src/app/Core/Graphics/Vertex/VAO.o"
	@echo "... src/app/Core/Graphics/Vertex/VAO.i"
	@echo "... src/app/Core/Graphics/Vertex/VAO.s"
	@echo "... src/app/Core/Graphics/Vertex/VBO.o"
	@echo "... src/app/Core/Graphics/Vertex/VBO.i"
	@echo "... src/app/Core/Graphics/Vertex/VBO.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

